### PR TITLE
New Feature: Watch Newer

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**
## Implementing grunt-newer:
- Moved site-specific options for Assemble into a separate property block named **site**. This is a new requirement to allow Stache to only execute a certain context of Assemble, and preserving some default values to be used by other tasks (in the case of our new feature, the task **expandFileMappings** will use the **assemble.defaults.files** glob pattern, but will then write a new file mapping for src-dest pairs, which **grunt-newer** requires).
- Added three separate contexts to **grunt-clean**: build, newer, and pages. This combination of contexts makes it possible for **grunt-newer** to work, because it is looking for a file in build/ and comparing it to a file in content/. If **grunt-clean** cleared out the build/ folder every time, **grunt-newer** wouldn't have any files to compare to. (Also, as a point of note, the Watch Newer feature will only be in effect for _pages_; if a partial or yaml file changes, the entire site will be rebuilt.) To accommodate this, each context performs a different level of clean-up. The build context works as it did before, cleaning out the entire build folder. The newer context will borrow the statement from the pages context, but then add pages to its array with an exclamation point (!) in front of their names so that they will not be cleaned out. 
- Added tests for **expandFileMappings**, **hook**, and **extendStacheConfig**
## Housekeeping:
- Comments throughout
- Removed **htmlmin** and some unused properties from the stache options object
- Separated the various hooks into two properties: hooks and filters; this will allow us to add any number of hooks or filters on a whim, instead of being constrained to those explicitly named in the stache object.
- Compiled both hook tasks into one, to accommodate future hooks, if needed
- Exposed all tasks and util methods, for testing purposes
- Moved tests/ directory to the root directory to give it more exposure to other areas of the package
- Added a separate test spec for **stache.js**

### CODE REVIEW

**Comment by Blackbaud-SteveBrush** [comment]
Forgot to mention: this feature is automatic for `stache serve`. To turn it off--and rebuild everything when something is changed--issue `stache serve:all`. This feature can also be turned on or off on a project-basis using the YAML variable `watchNewer:boolean`.

**Comment by Blackbaud-TripOtt** [comment]
Steve,

Looks like you are making good progress. Awesome.

After Stache Watch feature is complete, build a list of all new features, document them, and communicate.  Layout-panels and layout-panels-equal will need documenting, too.

-Trip

**Comment by Blackbaud-SteveBrush** [comment]
Thanks Trip, will do. I had to resubmit this PR because Log was still being referenced in helpers.js. Log is a dev dependency.

**Comment by Blackbaud-SteveBrush** [comment]
This isn't working for sandcastle implementations. Going to do some more debugging...

**Comment by Blackbaud-SteveBrush** [comment]
Alright, folks. I'm ready for another set of eyes to take a look at this before we merge. Got it working with sandcastle and jsdocs, at least on my local machine.

**Comment by Blackbaud-BobbyEarl** [comment]
Hey @Blackbaud-SteveBrush, a few remarks.

I think you'll find that changing the [iterator for pages](https://github.com/blackbaud/stache/blob/feature-grunt-newer/tasks/stache.js#L507) to always assume an array, causes problems with stache-jsdoc pages.  This is partly do as Assemble also supports a pages array or object.  You should be able to see this behavior by running the skyux-docs repo, but notice that there's no components showing up.

I appreciate you adding back support for the original style syntax of hooks.  I would suggest displaying a notice to users still using that syntax, as well as using 'deprecated' instead of 'depreciated.'  (pet peeve)

**Comment by Blackbaud-SteveBrush** [comment]
1) Regarding "deprecated" vs. "depreciated". I've seen both words used and didn't realize there was a best practice there. I looked it up and sure enough, "depreciated" doesn't really make sense in a programming context (you learn something new every day!). I updated every instance of that word in my code. 

2) Regarding deprecated hooks: I noticed that every time the "hook" task was run, it would check deprecated hooks again; this is inefficient, so I ended up isolating this check in a separate method and calling it once in build/serve. I also added specific warning messages for the deprecated hooks to let the user know those hooks will no longer be supported.

3) Regarding createAutoNav task: I reverted the pages array/object to what it was before. I think I was trying to reduce the number of variables in that particular method and attempted to use the "forEach" method instead. However, the "forEach" function wasn't working with objects, which is why I added the check for length. It's a silly mistake on my part, and I appreciate you letting me know the missing requirements here, especially in dealing with jsdocs.

**Comment by blackbaud-johnly** [comment]
Hey Steve,
I was out from the 18th on, so I never looked into this email. Do you still need people to look over something?

**Comment by Blackbaud-BobbyEarl** [comment]
Looks good to me @Blackbaud-SteveBrush Thanks for the hard work on this one!

**Pull request merged**
