### PR TITLE
Feature swagger

### PR DESCRIPTION
**Pull request by blackbaud-brandonhare**
Added the ability to generate a technical reference with a swagger.json file.

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Happy to take a look @blackbaud-brandonhare, but your PR is currently failing in TravisCI for linting rules.  Fix those then I can take another look.

**Comment by Blackbaud-BobbyEarl** [comment]
Everything seems to function as intended.  My only concern is always including the JS + swagger module for what I believe to be a relatively small use-case of Stache.  

With minimal changes to the work you've done, I believe we could move the inclusion of the JS file and AngularJS Module to only occur if they enable `swagger: true` in the `stache.yml` file.

Thoughts @Blackbaud-SteveBrush ?

**Comment by Blackbaud-TripOtt** [comment]
Makes sense. Steve?

http://ecx.images-amazon.com/images/I/51D8Pj2lqvL.jpg

**Comment by Blackbaud-SteveBrush** [comment]
@blackbaud-brandonhare : Echoing Bobby's comments, we could adjust the gruntfile to not include the Swagger stuff automatically. Instead, on the base layout, add a conditional for `swagger.input` (or `swagger.inputType`, if that property is a better choice). If this condition is met, include the minified version of **swagger-ui.js** and a minified version of the Stache Swagger Angular app on the base (this could be one file, generated by the gruntfile). This new, Angular app would be separate from the Stache Angular app. 

This would probably be the easiest solution, but feel free to come up with something else if you got any other ideas.

**Comment by blackbaud-brandonhare** [comment]
I think I've separated the Swagger module from the main Stache module pretty well. I removed the swagger module from the stache.yml by default. Seems like that's something we'd want to deliberately enable. Thanks for the feedback/assistance with this!

**Comment by Blackbaud-SteveBrush** [comment]
Approved. Let's get this documented, then we can update the NPM package.

[Approved with PullApprove](https://pullapprove.com/blackbaud/stache/pull-request/67/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/stache)

**Comment by Blackbaud-TripOtt** [comment]
Agreed.

**Comment by blackbaud-brandonhare** [comment]
I'll get that written first thing today.

**Pull request merged**
