### PR TITLE
Panels Equal Clean-up

### PR DESCRIPTION
**Pull request by blackbaud-brandonhare**
[Edit]

### CODE REVIEW

**Comment by blackbaud-brandonhare** [comment]
I have both panels and panels-equal patterns in this version. Each pattern displays the panels a bit differently, so I figured we should decide which one we wanted and just use that one. Thoughts?

**Comment by Blackbaud-SteveBrush** [comment]
@blackbaud-brandonhare: I went ahead and made the changes to this one. I removed the jQuery functions for equal height and did a find/replace to see where they were being used on the partials/layouts. As it stands now, the only occurrence of "panels equal" JavaScript and classes is in the `layout-panels-equal.hbs` file.

We can keep the layouts the same (`layout-panels`, `layout-panels-equal`), to avoid confusion.

Instead of converting the function to jQuery, I simply stole the Angular directive from the service catalog. We should (at least) test this on SKY UX Docs, SKY API Docs, UAT Kit Docs, and a site that uses your swagger spec.

**Comment by blackbaud-brandonhare** [comment]
I think this looks good @Blackbaud-SteveBrush. Tested with all of the sites you recommended and it works great. I actually like having both options still. Makes it a lot easier, since we don't have to deprecate panels-equal. I'm fine to merge this.

**Comment by Blackbaud-SteveBrush** [comment]
Thanks, @blackbaud-brandonhare. An admin needs to comment, "Approved", for all checks to pass (done).

**Comment by Blackbaud-SteveBrush** [comment]
Approved.

[Approved with PullApprove](https://pullapprove.com/blackbaud/stache/pull-request/77/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/stache)

**Pull request merged**
