### PR TITLE
Removed enableSearch endpoints/usage from OmnibarSearchSettingProvider

### LINKED ISSUE #74: Unable to set enableSearch in Omnibar
We are currently hard-coding setting `bbOmnibarConfig.enableSearch` to true, instead of reading it from `stacheConfig.omnibar.enableSearch`.

### PR DESCRIPTION
**Pull request by Blackbaud-BobbyEarl**
Fixes #74

### CODE REVIEW

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-BobbyEarl I believe this will require a `grunt build`.

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-SteveBrush That's correct. Travis CI runs `grunt build` as part of the `test` script in Travis CI.  I run a `grunt build` before doing manual testing of PRs, as well as before doing a release.

We could obviously run it prior to submitting the PR, but the reason I've typically not done that is to avoid possible merge conflicts.

**Comment by Blackbaud-SteveBrush** [comment]
Forgot Travis does that. I'll build locally for testing purposes.

**Comment by Blackbaud-SteveBrush** [comment]
Approved.

[Approved with PullApprove](https://pullapprove.com/blackbaud/stache/pull-request/75/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/stache)

**Pull request merged**
