### PR TITLE
Update helper.js file to apply SKY UX CSS classes to H1, H2, and H3 h…

### PR DESCRIPTION
**Pull request by blackbaud-johnly**
…eaders.

### CODE REVIEW

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-BobbyEarl: Mind taking a look at my updates? This change is fairly significant across the board. I'll continue testing on other sites I have locally.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-BobbyEarl: Thoughts?

**Options:**
1. Only apply classes to markdown headings. 
2. Restrict the classnames to main body headings only. 
3. Add a YAML variable that enables the feature (false by default)

Combine other SKY-related variables under the `skyux` umbrella:

```
skyux:
  - automateHeadingClassnames: false
  - enabled: true
  - version: 1.6.1
```

IMHO a combination of 1 and 3 would be ideal.

**Comment by Blackbaud-BobbyEarl** [comment]
I think we should really think about the use-cases and requirements for this change.  From my perspective, Stache is a vehicle for SKY UX sites, which means it should enforce SKY UX approved patterns.

For me, that means leaning towards your the second option.  Perhaps I'm not considering all the ramifications or globally (as far as Stache in concerned, within the main column content at least) applying the correct SKY UX classes.

**Comment by Blackbaud-SteveBrush** [comment]
The act of writing your own HTML for the headings is, in a sense, attempting to overwrite the default behavior of the Stache/UX engine. I understand that Stache is the best way someone can consume SKY UX, but it would be nice to have some level of customization to the theme ("SKY UX provides guidance and direction, while still offering flexibility," and, "SKY UX is tailored but not rigid."). 

We could modify the requirements of this PR a bit and say that:
- All headings generated from markdown will automatically receive the SKY UX classnames (i.e., only primary content headings). This way, the average author will generate SKY UX-satisfied content without even trying.
- If the user writes a heading in raw HTML, the classnames then become the responsibility of the author.

I feel like this method captures both the need for automatic classnames, as well as giving the content author control over the style, if needed. I've needed custom headings in the past, and being able to control the markup when necessary has been helpful.

**Comment by Blackbaud-BobbyEarl** [comment]
Finally had the chance to read your latest comment @Blackbaud-SteveBrush.  I'm on board.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-BobbyEarl, @blackbaud-brandonhare: Please test this PR before we merge. It should add SKY UX classnames _only_ to markdown headings in page content. Raw HTML headings should not receive the classnames automatically (nor headings outside of the primary content area).

**Comment by blackbaud-brandonhare** [comment]
@Blackbaud-SteveBrush: This worked for me. All markdown headers had the SKY UX classes, and the raw html ones did not.

**Comment by Blackbaud-BobbyEarl** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/stache/pull-request/81/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/stache)

**Pull request merged**
