### PR TITLE
added link to homepage for omnibar-title

### PR DESCRIPTION
**Pull request by blackbaud-brandonhare**
Updated the custom.css as well in the assets folder. Separate pull request.

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
I believe wrapping the .servicenow element in an A tag will cause CSS issues.  If you can solve those with CSS feel free to commit those, or perhaps something like the following...

var el = $('.servicename');
el.html('<a id="omnibar-link" href="{{ stache.config.base }}">' + el.text() + '</a>');

**Comment by blackbaud-brandonhare** [comment]
Changed the .wrap() to .wrapInner(). Puts the link around the content in the div. You would just have to change the CSS then to change the link color to whatever you wanted it to be.

**Comment by Blackbaud-BobbyEarl** [comment]
.wrapInner... much better!  Do you mind adding the necessary CSS to https://github.com/blackbaud-community/stache/blob/master/src/sass/_omnibar.scss to have the link be the same color as before?

**Comment by blackbaud-brandonhare** [comment]
Done and done. :)

**Comment by blackbaud-brandonhare** [comment]
I should probably remove it from the custom.css for stache docs as well.

**Comment by Blackbaud-TripOtt** [comment]
Brandon,  can we get a sample of how to implement within stache-docs?

**Comment by blackbaud-brandonhare** [comment]
It should be implemented automatically when you update Stache. :-) I can show what I did though in case they want to change where the link points for whatever reason.

**Pull request merged**
