### PR TITLE
Fixed column widths at phone breakpoint.

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**
The footer columns were overlapping each other, preventing some links from being clickable.

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Opinions on adding `<div class="clearfix visible-xs-block"></div>` to stop the 6's from possibly floating too much?

**Comment by Blackbaud-SteveBrush** [comment]
Where? Also, is the center column in the footer really necessary? In other words, is it being used, and how... (The issue is that the social icons column is stretching full-width at `xs` breakpoint, covering the footer menu.)

**Comment by blackbaud-brandonhare** [comment]
I think the middle column is used on some sites for status info. Like [stache docs](http://stache.docs.blackbaudhosting.com/).

**Comment by Blackbaud-SteveBrush** [comment]
So I guess we need to figure out how to display three (potential) columns in the footer, without the overlap. I'm going to fiddle with this a bit more...

**Comment by blackbaud-brandonhare** [comment]
Why not just make them col-xs-12 so they stack nicely? There typically isn't that much data in the footer where that would get lengthy.

**Comment by Blackbaud-SteveBrush** [comment]
Alright, added a little bit of both worlds. Moved the "center" column after the left and right columns, then used some bootstrap trickery to make them appear in the order we want them in on larger breakpoints. Adding the clearfix also helped with `xs` breakpoints.

**Comment by blackbaud-brandonhare** [comment]
I think this looks good. Works well when I tested it.

**Pull request merged**
